### ISSUE TITLE
requirements.txt / Pipfile

### ISSUE THREAD

**Issue by skela** [jankrib/xcomfort-python#1]
You wouldn't happen to have that handy? Can't seem to figure out what version of PyCrypto yer using.

Trying to use your package in some scripts I'm writing to start playing around with xComfort.

This is my Pipfile:

```
rx
PyCrypto
git+https://github.com/jankrib/xcomfort-python.git#egg=xcomfort
```

When I try to run my script I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from xcomfort import Bridge
  File "/home/skela/.local/lib/python3.8/site-packages/xcomfort/__init__.py", line 1, in <module>
    from .bridge import Bridge
  File "/home/skela/.local/lib/python3.8/site-packages/xcomfort/bridge.py", line 8, in <module>
    from .connection import Messages, SecureBridgeConnection, setup_secure_connection
  File "/home/skela/.local/lib/python3.8/site-packages/xcomfort/connection.py", line 13, in <module>
    from Crypto.Util.Padding import unpad, pad
ModuleNotFoundError: No module named 'Crypto.Util.Padding'
```

Most likely because I've got the wrong version (more recent version) of PyCrypto.

**Comment by skela** [comment]
Never mind, found it, wasn't Pycrypto yer using, but Pycryptodome.

```
rx
Pycryptodome
git+https://github.com/jankrib/xcomfort-python.git#egg=xcomfort
```
